theme: jekyll-theme-cayman
title: 'Self-Supervised Exploration<br>via Latent Bayesian Surprise'
description:
- Pietro Mazzaglia, Ozan Catal, Tim Verbelen, Bart Dhoedt<br>
- Ghent University<br>
- Self-supervision for Reinforcement Learning workshop (ICLR 2021)<br>