theme: jekyll-theme-cayman
title: 'Curiosity-Driven Exploration<br>via Latent Bayesian Surprise'
description:
- Pietro Mazzaglia, Ozan Catal, Tim Verbelen, Bart Dhoedt<br>
- IDLab, Ghent University<br>
- Accepted to AAAI-22 (oral)<br>
- Presented at Self-supervision for Reinforcement Learning workshop (ICLR 2021)<br>
buttons:
  Paper: 'https://arxiv.org/abs/2104.07495'
  Code: 'https://github.com/mazpie/lbs-exploration'
  NEW Code (ICML 23 work): 'https://github.com/mazpie/mastering-urlb'
google_analytics: G-DDG7GM42MN 