theme: jekyll-theme-cayman
title: 'Curiosity-Driven Exploration<br>via Latent Bayesian Surprise'
description:
- Pietro Mazzaglia, Ozan Catal, Tim Verbelen, Bart Dhoedt<br>
- IDLab, Ghent University<br>
- Accepted to AAAI-22<br>
- Presented at Self-supervision for Reinforcement Learning workshop (ICLR 2021)<br>
buttons:
  Conference Paper Coming Soon: ''
  Workshop Paper: 'https://arxiv.org/pdf/2104.07495.pdf'